version: '3'

services:
  element:
    build: .
    depends_on:
      - ganache
      - ipfs
      - mongo
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -h 0.0.0.0
    ports:
      - '8545:8545'
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    ports:
      - '8080:8080'
      - '5001:5001'
      - '4001:4001'
  mongo:
    image: mongo
    restart: always
    ports:
     - '27017:27017'
    # Disable logs for mongo
    logging:
      driver: none
